# Generated by Django 2.2.6 on 2019-11-02 18:09

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('body_html', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=30)),
                ('created_at', models.CharField(max_length=30)),
                ('handle', models.CharField(max_length=30)),
                ('updated_at', models.CharField(max_length=30)),
                ('published_at', models.CharField(max_length=30)),
                ('template_suffix', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=30)),
                ('published_scope', models.CharField(max_length=30)),
                ('admin_graphql_api_id', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
