# Generated by Django 2.2.6 on 2019-11-02 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_auto_20191102_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('admin_graphql_api_id', models.CharField(max_length=30)),
                ('barcode', models.CharField(max_length=30)),
                ('compare_at_price', models.CharField(max_length=30)),
                ('created_at', models.CharField(max_length=30)),
                ('fulfillment_service', models.CharField(max_length=30)),
                ('grams', models.CharField(max_length=30)),
                ('image_id', models.CharField(max_length=30)),
                ('inventory_item_id', models.CharField(max_length=30)),
                ('inventory_management', models.CharField(max_length=30)),
                ('inventory_policy', models.CharField(max_length=30)),
                ('inventory_quantity', models.CharField(max_length=30)),
                ('old_inventory_quantity', models.CharField(max_length=30)),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('required_shipping', models.CharField(max_length=30)),
                ('sku', models.CharField(max_length=30)),
                ('taxable', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('updated_at', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('weight_unit', models.CharField(max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
