# Generated by Django 2.2.6 on 2019-11-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='required_shipping',
            new_name='requires_shipping',
        ),
    ]
