# Generated by Django 2.2.6 on 2019-11-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0007_auto_20191102_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shopify.Product'),
        ),
    ]
