# Generated by Django 2.2.6 on 2019-11-03 12:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0008_auto_20191102_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('admin_graphql_api_id', models.CharField(max_length=30)),
                ('app_id', models.CharField(max_length=30)),
                ('browser_id', models.CharField(max_length=30)),
                ('buyer_accepts_marketing', models.CharField(max_length=30)),
                ('cancel_reason', models.CharField(max_length=30)),
                ('cancelled_at', models.CharField(max_length=30)),
                ('cart_token', models.CharField(max_length=30)),
                ('checkout_id', models.CharField(max_length=30)),
                ('checkout_token', models.CharField(max_length=30)),
                ('closed_at', models.CharField(max_length=30)),
                ('confirmed', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=30)),
                ('created_at', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=30)),
                ('customer_locale', models.CharField(max_length=30)),
                ('device_id', models.CharField(max_length=30)),
                ('discount_applications', models.CharField(max_length=30)),
                ('discount_codes', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('financial_status', models.CharField(max_length=30)),
                ('fulfillment_status', models.CharField(max_length=30)),
                ('fulfillments', models.CharField(max_length=30)),
                ('gateway', models.CharField(max_length=30)),
                ('landing_site', models.CharField(max_length=30)),
                ('landing_site_ref', models.CharField(max_length=30)),
                ('location_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('note_attributes', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('order_number', models.CharField(max_length=30)),
                ('order_status_url', models.CharField(max_length=30)),
                ('payment_gateway_names', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('presentment_currency', models.CharField(max_length=30)),
                ('processed_at', models.CharField(max_length=30)),
                ('processing_method', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=30)),
                ('referring_site', models.CharField(max_length=30)),
                ('refunds', models.CharField(max_length=30)),
                ('shipping_lines', models.CharField(max_length=30)),
                ('source_identifier', models.CharField(max_length=30)),
                ('source_name', models.CharField(max_length=30)),
                ('source_url', models.CharField(max_length=30)),
                ('subtotal_price', models.CharField(max_length=30)),
                ('subtotal_price_set', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=30)),
                ('tax_lines', models.CharField(max_length=30)),
                ('taxes_included', models.CharField(max_length=30)),
                ('test', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
