# Generated by Django 2.2.6 on 2019-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='browser_ip',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
